server:
  port: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/houxingwu/-.git
          username: houxingwu
          password: houxingwu951021
#4)入口
#    @SpringBootApplication
#@EnableEurekaClient //加入注册中心
#@EnableConfigServer //启用配置服务端
#5)测试
#  localhost:8848/application-plat-dev.yml