eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
  instance:
    prefer-ip-address: true
zuul:
  ignoredServices: '*'
  routes:
    plat:
      path: /plat/** #平台服务的请求路径
      serviceId: plat-service
  prefix: /services #请求前缀
